AWSTemplateFormatVersion: 2010-09-09

Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "amplify:*"
                Resource: "*"
        - PolicyName: GetSecret
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "secretsmanager:GetSecretValue"
                Resource: "arn:aws:secretsmanager:us-east-1:101127657027:secret:amplify-github-token-kpOv92"
  AmplifyApp:
    Type: "AWS::Amplify::App"
    Properties:
      Name: Blog
      Repository: "https://github.com/iamjaekim/iamjaekim.github.io"
      Description: Jae Wook Kim Blog
      AccessToken: "{{resolve:secretsmanager:amplify-github-token:SecretString:amplify-github}}"
      BuildSpec: |-
        version: 0.1
        frontend:
          phases:
            preBuild:
              commands:
                - bundle install --path vendor/bundle
            build:
              commands:
                - JEKYLL_ENV=production bundle exec jekyll build
          artifacts:
            baseDirectory: _site
            files:
              - '**/*'
          cache:
            paths:
              - 'vendor/**/*'
      Tags:
        - Key: Name
          Value: Blog
      IAMServiceRole: !GetAtt AmplifyRole.Arn

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: deploy
      AppId: !GetAtt AmplifyApp.AppId
      Description: deploy Branch
      EnableAutoBuild: true
      Tags:
        - Key: Name
          Value: blog

  # AmplifyDomain:
  #   Type: AWS::Amplify::Domain
  #   Properties:
  #     DomainName: !Ref Domain
  #     AppId: !GetAtt AmplifyApp.AppId
  #     SubDomainSettings:
  #       - Prefix: master
  #         BranchName: !GetAtt AmplifyBranch.BranchName

Outputs:
  DefaultDomain:
    Value: !GetAtt AmplifyApp.DefaultDomain

  # MasterBranchUrl:
  #   Value: !Join [ ".", [ !GetAtt AmplifyBranch.BranchName, !GetAtt AmplifyDomain.DomainName ]]
